### ISSUE TITLE
The netstat command

### ISSUE THREAD

**Issue by albertgubanja** [AndemusGBJ/WinSecurityFeatures#16]

**Comment by albertgubanja** [comment]
Write a blog and upload a .docx file before March 6th, 2023.
Name the file as the title of the blog to be written.

**Comment by devgenix** [comment]
> Write a blog and upload a .docx file before March 6th, 2023. Name the file as the title of the blog to be written.

I already started writing this in Markdown. Can I continue with that?

**Comment by albertgubanja** [comment]
There is no problem. After that, copy the text into a Word document and upload the file on GitHub.
We are going to discuss during the today meeting

**Comment by devgenix** [comment]
I thought to create a branch, add my documents in Markdown and push.

**Comment by albertgubanja** [comment]
Do what is possible. The objective is to get the content.

**Comment by devgenix** [comment]
> Do what is possible. The objective is to get the content.

@AndemusGBJ I've worked on this and raised a PR #19
